Repository Olanetsoft/awesome-hackathon-projects, pull requests merged in 2022-10, with the labels that each got.

#7 Fix: Reformat & update readme with Contributors info and contributing…
  README.md
Labels: enhancement, good first issue, hacktoberfest

#9 Fix: #8 Sort Projects Alphabetically
  README.md
Labels: bug, enhancement, hacktoberfest

#10 Display projects in tabular format
  README.md
Labels: documentation, enhancement, hacktoberfest

#13 Fixed the numbering and alphabets
  README.md
Labels: documentation, enhancement, hacktoberfest
